"""mirakl_db.py — Module 5 (Mirakl: Tesco + B&Q) schema + idempotent upserts.

Two new tables plus one additive column on the existing pl_line_items:

  mirakl_order_state   per-order Mirakl-side state machine so the sync never
                       double-accepts / double-ships (WAITING_ACCEPTANCE →
                       ACCEPTED → SHIPPING).
  mirakl_transactions  the financial ledger (order amount, shipping, commission,
                       VAT per order/order-line). raw_payload stores the WHOLE JSON
                       row — Mirakl documents that new fields/enum values appear
                       over time, so the parser must never fail on unknown ones.
                       Idempotent via a uniqueness constraint.
  pl_line_items.channel  additive column ('amazon' default) so Mirakl order lines
                       can share the canonical order/P&L table, tagged by channel.

Dual-backend through db.py (SQLite locally, Postgres on Railway), same conventions
as the pl_* / ppc_* tables. NOTHING here calls Amazon or Mirakl — pure storage.
"""
import json
import logging
from datetime import datetime, timezone

import db

log = logging.getLogger(__name__)
DB_PATH = "bsr_history.db"

MIRAKL_ACCOUNTS = ("tesco", "bandq")
# Mirakl-side order states we track (a superset is tolerated; these drive the jobs).
STATE_WAITING = "WAITING_ACCEPTANCE"
STATE_ACCEPTED = "ACCEPTED"
STATE_SHIPPING = "SHIPPING"


def _now():
    return datetime.now(timezone.utc).isoformat()


def get_db(db_path=DB_PATH):
    conn = db.connect(db_path)
    if not db.is_postgres():
        conn.execute("PRAGMA journal_mode=WAL")
    return conn


def _column_exists(conn, table, col):
    if db.is_postgres():
        return conn.execute(
            "SELECT 1 FROM information_schema.columns WHERE table_name=? AND column_name=?",
            (table, col)).fetchone() is not None
    rows = conn.execute(f"PRAGMA table_info({table})").fetchall()
    return any((r["name"] if not isinstance(r, (tuple, list)) else r[1]) == col for r in rows)


def init_mirakl_schema(db_path=DB_PATH):
    conn = get_db(db_path)
    pg = db.is_postgres()
    MONEY = "NUMERIC(14,4)" if pg else "REAL"
    IDCOL = ("BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY"
             if pg else "INTEGER PRIMARY KEY AUTOINCREMENT")

    conn.execute(f"""
        CREATE TABLE IF NOT EXISTS mirakl_order_state (
            account_id   TEXT NOT NULL,        -- 'tesco' | 'bandq'
            order_id     TEXT NOT NULL,
            state        TEXT,                 -- WAITING_ACCEPTANCE | ACCEPTED | SHIPPING | ...
            accepted_at  TEXT,
            shipped_at   TEXT,
            tracking_number TEXT,
            carrier_code TEXT,
            raw_payload  TEXT,                 -- last-seen order JSON (tolerant of new fields)
            updated_at   TEXT NOT NULL,
            PRIMARY KEY (account_id, order_id)
        )
    """)

    conn.execute(f"""
        CREATE TABLE IF NOT EXISTS mirakl_transactions (
            id                         {IDCOL},
            account_id                 TEXT NOT NULL,     -- 'tesco' | 'bandq'
            order_id                   TEXT NOT NULL,
            order_line_id              TEXT,
            transaction_type           TEXT NOT NULL,     -- ORDER_AMOUNT, COMMISSION_FEE, ... (enum grows)
            amount                     {MONEY},
            currency                   TEXT,
            transaction_date           TEXT,
            payment_state              TEXT,              -- PENDING|PAYABLE|PAID|NOT_APPLICABLE|RESERVE
            accounting_document_number TEXT,
            raw_payload                TEXT NOT NULL,     -- the full JSON row, verbatim
            created_at                 TEXT NOT NULL
        )
    """)
    # idempotency: one row per (account, order, type, accounting doc). accounting_document_number
    # can be NULL early in the lifecycle, so we also key on order_line_id via a COALESCE'd unique
    # index that works on both backends.
    conn.execute("""
        CREATE UNIQUE INDEX IF NOT EXISTS uq_mirakl_txn
        ON mirakl_transactions(account_id, order_id, transaction_type,
                               COALESCE(order_line_id,''), COALESCE(accounting_document_number,''))
    """)
    conn.execute("CREATE INDEX IF NOT EXISTS idx_mirakl_txn_date ON mirakl_transactions(account_id, transaction_date)")

    # additive: channel discriminator on the shared canonical order table.
    if not _column_exists(conn, "pl_line_items", "channel"):
        conn.execute("ALTER TABLE pl_line_items ADD COLUMN channel TEXT")
    # existing rows are all Amazon
    conn.execute("UPDATE pl_line_items SET channel='amazon' WHERE channel IS NULL OR channel=''")

    conn.commit()
    conn.close()
    log.info("Module 5 (Mirakl) schema initialised.")


# ── order state machine ──────────────────────────────────────────────────────

def upsert_order_state(account_id, order_id, state=None, tracking_number=None,
                       carrier_code=None, raw=None, accepted=False, shipped=False,
                       db_path=DB_PATH):
    conn = get_db(db_path)
    now = _now()
    existing = conn.execute(
        "SELECT * FROM mirakl_order_state WHERE account_id=? AND order_id=?",
        (account_id, order_id)).fetchone()
    raw_json = json.dumps(raw) if raw is not None else (dict(existing).get("raw_payload") if existing else None)
    if existing:
        cur = dict(existing)
        conn.execute(
            """UPDATE mirakl_order_state SET state=?, tracking_number=?, carrier_code=?,
               accepted_at=?, shipped_at=?, raw_payload=?, updated_at=?
               WHERE account_id=? AND order_id=?""",
            (state if state is not None else cur.get("state"),
             tracking_number if tracking_number is not None else cur.get("tracking_number"),
             carrier_code if carrier_code is not None else cur.get("carrier_code"),
             now if accepted else cur.get("accepted_at"),
             now if shipped else cur.get("shipped_at"),
             raw_json, now, account_id, order_id))
    else:
        conn.execute(
            """INSERT INTO mirakl_order_state
               (account_id, order_id, state, tracking_number, carrier_code,
                accepted_at, shipped_at, raw_payload, updated_at)
               VALUES (?,?,?,?,?,?,?,?,?)""",
            (account_id, order_id, state, tracking_number, carrier_code,
             now if accepted else None, now if shipped else None, raw_json, now))
    conn.commit()
    conn.close()


def get_orders_in_state(account_id, state, db_path=DB_PATH):
    conn = get_db(db_path)
    rows = conn.execute(
        "SELECT * FROM mirakl_order_state WHERE account_id=? AND state=?",
        (account_id, state)).fetchall()
    conn.close()
    return [dict(r) for r in rows]


# ── financial ledger (idempotent) ────────────────────────────────────────────

def upsert_transaction(account_id, txn, db_path=DB_PATH):
    """Insert one financial row idempotently. `txn` is a dict straight off Mirakl;
    unknown keys are preserved in raw_payload and never cause a failure. Returns
    True if a new row was written, False if it already existed (dedup)."""
    conn = get_db(db_path)
    row = (account_id,
           str(txn.get("order_id") or ""),
           (str(txn["order_line_id"]) if txn.get("order_line_id") is not None else None),
           str(txn.get("transaction_type") or txn.get("type") or "UNKNOWN"),
           _num(txn.get("amount")),
           txn.get("currency") or txn.get("currency_iso_code"),
           txn.get("transaction_date") or txn.get("date"),
           txn.get("payment_state") or txn.get("state"),
           (str(txn["accounting_document_number"]) if txn.get("accounting_document_number") is not None else None),
           json.dumps(txn, default=str),
           _now())
    try:
        conn.execute(
            """INSERT INTO mirakl_transactions
               (account_id, order_id, order_line_id, transaction_type, amount, currency,
                transaction_date, payment_state, accounting_document_number, raw_payload, created_at)
               VALUES (?,?,?,?,?,?,?,?,?,?,?)""", row)
        conn.commit()
        written = True
    except Exception as e:
        # unique-violation → already have it (idempotent re-run). Any other error re-raises.
        msg = str(e).lower()
        conn.rollback() if hasattr(conn, "rollback") else None
        if "unique" in msg or "duplicate" in msg:
            written = False
        else:
            conn.close()
            raise
    conn.close()
    return written


def _num(v):
    if v is None:
        return None
    try:
        return float(str(v).replace(",", "").replace("£", "").strip())
    except (ValueError, TypeError):
        return None


def transaction_count(account_id=None, db_path=DB_PATH):
    conn = get_db(db_path)
    if account_id:
        n = conn.execute("SELECT COUNT(*) AS n FROM mirakl_transactions WHERE account_id=?",
                         (account_id,)).fetchone()["n"]
    else:
        n = conn.execute("SELECT COUNT(*) AS n FROM mirakl_transactions").fetchone()["n"]
    conn.close()
    return n
