"""module8_accounts.py — Module 8 data layer: user accounts (master + users).

Safe, OPT-IN authentication for commercialisation:
  * The app stays FULLY OPEN (current behaviour) until the first master account is
    created — so deploying this can never lock you out.
  * Once at least one active user exists, login is required (enforced in
    dashboard_accounts.before_request).

Roles:
  master — full access, can manage users and settings.
  user   — day-to-day access; blocked from admin areas (/accounts, /settings, /admin).

Passwords are stored only as salted hashes (werkzeug). Plain passwords are never kept.
Dual-backend via db.py, same conventions as the rest of the app.
"""
import json
import logging
from datetime import datetime, timezone

from werkzeug.security import generate_password_hash, check_password_hash

import db

log = logging.getLogger(__name__)
DB_PATH = "bsr_history.db"
ROLES = ("master", "user")
ADMIN_PREFIXES = ("/accounts", "/settings", "/admin")   # master-only areas


def _now():
    return datetime.now(timezone.utc).isoformat()


def get_db(db_path=DB_PATH):
    conn = db.connect(db_path)
    if not db.is_postgres():
        conn.execute("PRAGMA journal_mode=WAL")
    return conn


def init_accounts_schema(db_path=DB_PATH):
    conn = get_db(db_path)
    IDCOL = ("BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY"
             if db.is_postgres() else "INTEGER PRIMARY KEY AUTOINCREMENT")
    conn.execute(f"""
        CREATE TABLE IF NOT EXISTS app_users (
            id          {IDCOL},
            username    TEXT NOT NULL UNIQUE,
            pw_hash     TEXT NOT NULL,
            role        TEXT NOT NULL DEFAULT 'user',
            access      TEXT,
            active      INTEGER NOT NULL DEFAULT 1,
            created_at  TEXT,
            last_login  TEXT
        )""")
    if hasattr(conn, "commit"):
        conn.commit()
    log.info("Module 8 accounts schema initialised.")


# ── queries ──────────────────────────────────────────────────────────────────

def any_active_users():
    """True once at least one active account exists → login enforcement turns on.
    Guarded so a DB hiccup fails OPEN (never locks the owner out by accident)."""
    try:
        conn = get_db()
        r = conn.execute("SELECT COUNT(*) AS n FROM app_users WHERE active=1").fetchone()
        return bool(dict(r)["n"]) if r else False
    except Exception as e:
        log.warning("any_active_users check failed (treating as open): %s", e)
        return False


def list_users():
    conn = get_db()
    rows = conn.execute(
        "SELECT id, username, role, access, active, created_at, last_login "
        "FROM app_users ORDER BY role DESC, username").fetchall()
    out = []
    for r in rows:
        d = dict(r)
        d["access"] = json.loads(d["access"]) if d.get("access") else None
        out.append(d)
    return out


def get_user(uid):
    conn = get_db()
    r = conn.execute("SELECT * FROM app_users WHERE id=?", (uid,)).fetchone()
    if not r:
        return None
    d = dict(r)
    d["access"] = json.loads(d["access"]) if d.get("access") else None
    return d


def create_user(username, password, role="user", access=None):
    username = (username or "").strip()
    if not username or not password:
        raise ValueError("username and password required")
    if role not in ROLES:
        role = "user"
    conn = get_db()
    conn.execute(
        "INSERT INTO app_users (username, pw_hash, role, access, active, created_at) "
        "VALUES (?,?,?,?,1,?)",
        (username, generate_password_hash(password), role,
         json.dumps(access) if access else None, _now()))
    if hasattr(conn, "commit"):
        conn.commit()


def verify(username, password):
    """Return the user dict on valid credentials (and stamp last_login), else None."""
    conn = get_db()
    r = conn.execute("SELECT * FROM app_users WHERE username=? AND active=1",
                     ((username or "").strip(),)).fetchone()
    if not r:
        return None
    d = dict(r)
    if not check_password_hash(d["pw_hash"], password or ""):
        return None
    conn.execute("UPDATE app_users SET last_login=? WHERE id=?", (_now(), d["id"]))
    if hasattr(conn, "commit"):
        conn.commit()
    d["access"] = json.loads(d["access"]) if d.get("access") else None
    return d


def set_active(uid, active):
    conn = get_db()
    conn.execute("UPDATE app_users SET active=? WHERE id=?", (1 if active else 0, uid))
    if hasattr(conn, "commit"):
        conn.commit()


def set_password(uid, password):
    if not password:
        raise ValueError("password required")
    conn = get_db()
    conn.execute("UPDATE app_users SET pw_hash=? WHERE id=?",
                 (generate_password_hash(password), uid))
    if hasattr(conn, "commit"):
        conn.commit()


def is_admin_path(path):
    return any(path == p or path.startswith(p + "/") or path.startswith(p)
               for p in ADMIN_PREFIXES)
