"""module7_purchasing.py — Module 7 data layer: suppliers + purchase orders.

Three tables, dual-backend (Postgres on Railway / SQLite locally) via db.py, same
conventions as the rest of the app:

  suppliers        — who you buy from (name, contact, default lead-time days).
  purchase_orders  — one header row per PO (supplier, status, reference, dates).
  po_lines         — the SKUs/quantities/costs on a PO.

Reorder suggestions are computed live from the inventory snapshot + sales velocity
(module6_inventory): for anything at "reorder"/"out", suggest ordering enough to reach
a target days-of-cover. No network here — pure storage + a suggestion query.
"""
import logging
from datetime import datetime, timezone

import db

log = logging.getLogger(__name__)
DB_PATH = "bsr_history.db"
STATUSES = ("draft", "sent", "received", "cancelled")
DEFAULT_TARGET_DAYS = 30


def _now():
    return datetime.now(timezone.utc).isoformat()


def get_db(db_path=DB_PATH):
    conn = db.connect(db_path)
    if not db.is_postgres():
        conn.execute("PRAGMA journal_mode=WAL")
    return conn


# ── schema ───────────────────────────────────────────────────────────────────

def init_purchasing_schema(db_path=DB_PATH):
    conn = get_db(db_path)
    pg = db.is_postgres()
    MONEY = "NUMERIC(14,4)" if pg else "REAL"
    IDCOL = ("BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY"
             if pg else "INTEGER PRIMARY KEY AUTOINCREMENT")
    conn.execute(f"""
        CREATE TABLE IF NOT EXISTS suppliers (
            id          {IDCOL},
            name        TEXT NOT NULL,
            contact     TEXT,
            email       TEXT,
            lead_days   INTEGER DEFAULT 14,
            notes       TEXT,
            created_at  TEXT
        )""")
    conn.execute(f"""
        CREATE TABLE IF NOT EXISTS purchase_orders (
            id           {IDCOL},
            supplier_id  INTEGER,
            reference    TEXT,
            status       TEXT NOT NULL DEFAULT 'draft',
            notes        TEXT,
            created_at   TEXT,
            updated_at   TEXT
        )""")
    conn.execute(f"""
        CREATE TABLE IF NOT EXISTS po_lines (
            id          {IDCOL},
            po_id       INTEGER NOT NULL,
            canonical_sku TEXT,
            asin        TEXT,
            title       TEXT,
            quantity    INTEGER NOT NULL DEFAULT 0,
            unit_cost   {MONEY},
            created_at  TEXT
        )""")
    conn.execute("CREATE INDEX IF NOT EXISTS ix_poline_po ON po_lines(po_id)")
    if hasattr(conn, "commit"):
        conn.commit()
    log.info("Module 7 purchasing schema initialised.")


# ── suppliers ────────────────────────────────────────────────────────────────

def list_suppliers():
    conn = get_db()
    return [dict(r) for r in conn.execute(
        "SELECT * FROM suppliers ORDER BY name").fetchall()]


def add_supplier(name, contact=None, email=None, lead_days=14, notes=None):
    conn = get_db()
    conn.execute(
        "INSERT INTO suppliers (name, contact, email, lead_days, notes, created_at) "
        "VALUES (?,?,?,?,?,?)", (name, contact, email, int(lead_days or 14), notes, _now()))
    if hasattr(conn, "commit"):
        conn.commit()


# ── purchase orders ──────────────────────────────────────────────────────────

def create_po(supplier_id=None, reference=None, notes=None):
    conn = get_db()
    now = _now()
    cur = conn.execute(
        "INSERT INTO purchase_orders (supplier_id, reference, status, notes, created_at, updated_at) "
        "VALUES (?,?, 'draft', ?,?,?)", (supplier_id or None, reference, notes, now, now))
    if hasattr(conn, "commit"):
        conn.commit()
    # fetch the new id (portable: last row by created_at + reference)
    row = conn.execute(
        "SELECT id FROM purchase_orders ORDER BY id DESC LIMIT 1").fetchone()
    return dict(row)["id"] if row else None


def add_line(po_id, canonical_sku=None, asin=None, title=None, quantity=0, unit_cost=None):
    conn = get_db()
    conn.execute(
        "INSERT INTO po_lines (po_id, canonical_sku, asin, title, quantity, unit_cost, created_at) "
        "VALUES (?,?,?,?,?,?,?)",
        (po_id, canonical_sku, asin, title, int(quantity or 0), unit_cost, _now()))
    _touch(conn, po_id)
    if hasattr(conn, "commit"):
        conn.commit()


def set_status(po_id, status):
    if status not in STATUSES:
        raise ValueError(f"bad status {status!r}")
    conn = get_db()
    conn.execute("UPDATE purchase_orders SET status=?, updated_at=? WHERE id=?",
                 (status, _now(), po_id))
    if hasattr(conn, "commit"):
        conn.commit()


def delete_line(line_id, po_id):
    conn = get_db()
    conn.execute("DELETE FROM po_lines WHERE id=?", (line_id,))
    _touch(conn, po_id)
    if hasattr(conn, "commit"):
        conn.commit()


def _touch(conn, po_id):
    conn.execute("UPDATE purchase_orders SET updated_at=? WHERE id=?", (_now(), po_id))


def list_pos():
    conn = get_db()
    rows = conn.execute("""
        SELECT po.*, s.name AS supplier_name,
               (SELECT COUNT(*) FROM po_lines l WHERE l.po_id = po.id) AS line_count,
               (SELECT COALESCE(SUM(l.quantity),0) FROM po_lines l WHERE l.po_id = po.id) AS unit_count,
               (SELECT COALESCE(SUM(l.quantity * COALESCE(l.unit_cost,0)),0) FROM po_lines l WHERE l.po_id = po.id) AS total_cost
        FROM purchase_orders po
        LEFT JOIN suppliers s ON s.id = po.supplier_id
        ORDER BY po.id DESC""").fetchall()
    return [dict(r) for r in rows]


def get_po(po_id):
    conn = get_db()
    po = conn.execute("""
        SELECT po.*, s.name AS supplier_name FROM purchase_orders po
        LEFT JOIN suppliers s ON s.id = po.supplier_id WHERE po.id=?""", (po_id,)).fetchone()
    if not po:
        return None, []
    lines = conn.execute("SELECT * FROM po_lines WHERE po_id=? ORDER BY id", (po_id,)).fetchall()
    return dict(po), [dict(r) for r in lines]


# ── reorder suggestions (from inventory + velocity) ──────────────────────────

def reorder_suggestions(target_days=DEFAULT_TARGET_DAYS):
    """Anything at 'reorder' or 'out' with recent sales → suggest a quantity that
    reaches `target_days` of cover. Uses module6_inventory's live enrichment."""
    try:
        import module6_inventory as inv
    except Exception as e:
        log.warning("reorder suggestions: inventory module unavailable: %s", e)
        return []
    rows = inv.list_inventory()
    inv.enrich_with_prediction(rows)
    out = []
    for r in rows:
        if r.get("stock_status") not in ("reorder", "out"):
            continue
        daily = r.get("daily_rate") or 0.0
        target_units = int(round(daily * target_days))
        suggest = max(target_units - int(r.get("quantity") or 0), 0)
        if suggest <= 0 and r.get("stock_status") == "out":
            suggest = max(target_units, 1)   # out of stock but some pace → at least reorder to target
        out.append({
            "canonical_sku": r.get("canonical_sku") or r.get("seller_sku"),
            "seller_sku": r.get("seller_sku"),
            "asin": r.get("asin"),
            "title": r.get("title"),
            "quantity": r.get("quantity"),
            "daily_rate": daily,
            "days_cover": r.get("days_cover"),
            "status": r.get("stock_status"),
            "suggested_qty": suggest,
        })
    out.sort(key=lambda x: (x["status"] != "out", x["days_cover"] if x["days_cover"] is not None else 1e9))
    return out
