"""module5_labels_db.py — Module 5a data layer: package defaults + shipment labels.

Two tables, dual-backend (Postgres on Railway / SQLite locally) via db.py, same
"seed once, dashboard is source of truth" pattern as the COGS tables:

  sku_package_defaults — per-canonical weight/dimensions for Buy-Shipping quotes.
      Seeded once from the SP-API Catalog Items API (dimensions_backfill.py), then
      editable in the dashboard. Falls back to manual entry when Amazon has no
      declared dimensions for an ASIN. Keyed UNIQUE(account_id, canonical_sku).

  shipment_labels — one row per purchased Amazon Buy-Shipping label. Keyed
      UNIQUE(account_id, order_id) for idempotency (same convention as the rest of
      the project). This is the future live source of PER-ORDER (exact) postage
      events for Module 2's postage badge, instead of waiting on order-report
      ingestion.

No SP-API or network here — pure storage. Amazon calls live in dimensions_backfill.py
(read-only Catalog) and the label pipeline modules (quote/purchase), built separately.
"""
import logging
from datetime import datetime, timezone

import db

log = logging.getLogger(__name__)
DB_PATH = "bsr_history.db"


def get_db(db_path=DB_PATH):
    conn = db.connect(db_path)
    if not db.is_postgres():
        conn.execute("PRAGMA journal_mode=WAL")
    return conn


def _now():
    return datetime.now(timezone.utc).isoformat()


# ── schema ───────────────────────────────────────────────────────────────────

def init_labels_schema(db_path=DB_PATH):
    conn = get_db(db_path)
    pg = db.is_postgres()
    MONEY = "NUMERIC(14,4)" if pg else "REAL"
    DIM = "NUMERIC(10,2)" if pg else "REAL"
    IDCOL = ("BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY"
             if pg else "INTEGER PRIMARY KEY AUTOINCREMENT")

    conn.execute(f"""
        CREATE TABLE IF NOT EXISTS sku_package_defaults (
            id             {IDCOL},
            account_id     TEXT NOT NULL,
            canonical_sku  TEXT NOT NULL,           -- resolved via cogs_aliases (sku_aliases)
            asin           TEXT,                    -- for catalog re-lookups
            weight_g       INTEGER,
            length_cm      {DIM},
            width_cm       {DIM},
            height_cm      {DIM},
            source         TEXT NOT NULL DEFAULT 'manual',   -- 'amazon_catalog' | 'manual'
            updated_at     TEXT NOT NULL,
            UNIQUE(account_id, canonical_sku)
        )
    """)
    conn.execute("CREATE INDEX IF NOT EXISTS idx_pkgdef_acct ON sku_package_defaults(account_id)")

    conn.execute(f"""
        CREATE TABLE IF NOT EXISTS shipment_labels (
            id                {IDCOL},
            account_id        TEXT NOT NULL,
            order_id          TEXT NOT NULL,         -- Amazon order ID
            order_item_id     TEXT,                  -- nullable
            asin              TEXT,
            sku               TEXT,
            carrier           TEXT,                  -- 'amazon_buy_shipping' this phase
            service_name      TEXT,
            service_code      TEXT,
            label_cost        {MONEY},
            currency          TEXT,
            tracking_number   TEXT,
            file_type         TEXT,                  -- 'PDF' | 'PNG'
            label_file_path   TEXT,
            packing_slip_path TEXT,
            combined_pdf_path TEXT,
            purchased_at      TEXT,
            status            TEXT NOT NULL DEFAULT 'quoted',  -- quoted|purchased|printed|failed
            created_at        TEXT NOT NULL,
            UNIQUE(account_id, order_id)
        )
    """)
    conn.execute("CREATE INDEX IF NOT EXISTS idx_shiplabel_acct_status "
                 "ON shipment_labels(account_id, status)")
    conn.commit()
    conn.close()
    log.info("Module 5a labels schema initialised.")


# ── sku_package_defaults CRUD ────────────────────────────────────────────────

def upsert_package_default(account_id, canonical_sku, asin=None, weight_g=None,
                           length_cm=None, width_cm=None, height_cm=None,
                           source="manual", db_path=DB_PATH):
    """Insert or update the package default for (account, canonical). Idempotent —
    re-running the backfill or re-saving from the settings page overwrites in place."""
    conn = get_db(db_path)
    conn.execute(
        "INSERT INTO sku_package_defaults "
        "(account_id, canonical_sku, asin, weight_g, length_cm, width_cm, height_cm, source, updated_at) "
        "VALUES (?,?,?,?,?,?,?,?,?) "
        "ON CONFLICT(account_id, canonical_sku) DO UPDATE SET "
        "asin=excluded.asin, weight_g=excluded.weight_g, length_cm=excluded.length_cm, "
        "width_cm=excluded.width_cm, height_cm=excluded.height_cm, source=excluded.source, "
        "updated_at=excluded.updated_at",
        (account_id, canonical_sku, asin, weight_g, length_cm, width_cm, height_cm, source, _now()))
    conn.commit()
    conn.close()


def get_package_default(account_id, canonical_sku, db_path=DB_PATH):
    conn = get_db(db_path)
    row = conn.execute(
        "SELECT * FROM sku_package_defaults WHERE account_id=? AND canonical_sku=?",
        (account_id, canonical_sku)).fetchone()
    conn.close()
    return dict(row) if row else None


def list_package_defaults(account_id=None, db_path=DB_PATH):
    conn = get_db(db_path)
    if account_id and account_id != "all":
        rows = conn.execute(
            "SELECT * FROM sku_package_defaults WHERE account_id=? ORDER BY canonical_sku",
            (account_id,)).fetchall()
    else:
        rows = conn.execute(
            "SELECT * FROM sku_package_defaults ORDER BY account_id, canonical_sku").fetchall()
    conn.close()
    return [dict(r) for r in rows]


def count_package_defaults(db_path=DB_PATH):
    """{'total': n, 'amazon_catalog': n, 'manual': n, 'complete': n} — 'complete' = has
    weight and all three dims (usable for a quote without manual entry)."""
    conn = get_db(db_path)
    rows = conn.execute("SELECT source, weight_g, length_cm, width_cm, height_cm "
                        "FROM sku_package_defaults").fetchall()
    conn.close()
    out = {"total": 0, "amazon_catalog": 0, "manual": 0, "complete": 0}
    for r in rows:
        out["total"] += 1
        out[r["source"]] = out.get(r["source"], 0) + 1
        if all(r[k] is not None for k in ("weight_g", "length_cm", "width_cm", "height_cm")):
            out["complete"] += 1
    return out


# ── shipment_labels CRUD (used by the quote/purchase pipeline, built later) ───

def get_label(account_id, order_id, db_path=DB_PATH):
    conn = get_db(db_path)
    row = conn.execute(
        "SELECT * FROM shipment_labels WHERE account_id=? AND order_id=?",
        (account_id, order_id)).fetchone()
    conn.close()
    return dict(row) if row else None


def upsert_label(account_id, order_id, fields, db_path=DB_PATH):
    """Insert or update a label row. `fields` is a dict of any shipment_labels columns
    (order_item_id, asin, sku, carrier, service_name, service_code, label_cost, currency,
    tracking_number, file_type, label_file_path, packing_slip_path, combined_pdf_path,
    purchased_at, status). Keyed UNIQUE(account_id, order_id)."""
    cols = ["order_item_id", "asin", "sku", "carrier", "service_name", "service_code",
            "label_cost", "currency", "tracking_number", "file_type", "label_file_path",
            "packing_slip_path", "combined_pdf_path", "purchased_at", "status"]
    vals = {c: fields.get(c) for c in cols if c in fields}
    conn = get_db(db_path)
    setcols = list(vals.keys())
    placeholders = ["account_id", "order_id"] + setcols + ["created_at"]
    row_vals = [account_id, order_id] + [vals[c] for c in setcols] + [_now()]
    update_clause = ", ".join(f"{c}=excluded.{c}" for c in setcols) or "status=excluded.status"
    conn.execute(
        f"INSERT INTO shipment_labels ({', '.join(placeholders)}) "
        f"VALUES ({', '.join('?' for _ in placeholders)}) "
        f"ON CONFLICT(account_id, order_id) DO UPDATE SET {update_clause}",
        row_vals)
    conn.commit()
    conn.close()


def list_labels(account_id=None, status=None, db_path=DB_PATH):
    conn = get_db(db_path)
    clauses, params = [], []
    if account_id and account_id != "all":
        clauses.append("account_id=?")
        params.append(account_id)
    if status:
        clauses.append("status=?")
        params.append(status)
    where = ("WHERE " + " AND ".join(clauses)) if clauses else ""
    rows = conn.execute(
        f"SELECT * FROM shipment_labels {where} ORDER BY created_at DESC", params).fetchall()
    conn.close()
    return [dict(r) for r in rows]
