"""pl_expenses.py — business overheads / fixed expenses (Module 2 side-car).

Overheads are kept COMPLETELY SEPARATE from per-order COGS. They are never mixed
into a product's per-order cost; they sit alongside the P&L and are subtracted at
the SUMMARY level only (business-wide bottom line). Per-order COGS logic is untouched.

Two kinds live in one table (`pl_overheads.kind`):
  * 'recurring' — a MONTHLY overhead (rent, labour, utilities, software, packaging
    bought in bulk). `amount` is the per-month figure; active over [start_date, end_date]
    (end_date NULL = still running). To change a value (e.g. rent rises) you end-date
    the old row and add a new one — history is preserved.
  * 'oneoff'   — a single dated expense (equipment, a bulk packaging order, a
    prep-centre bill). `on_date` is when it hit; `amount` is the whole cost.

Every row carries account_id ('M4Mart_UK' | the second account | 'shared'); money is
NUMERIC(14,4) on Postgres / REAL on SQLite, same as the rest of the schema.

compute_overheads() PRO-RATES the monthly recurring lines to the period being viewed
(daily rate = monthly ÷ 30.4375) and adds any one-offs dated inside the window. It does
NOT allocate anything down to per-ASIN/product — business-wide only, by design.
"""
import logging
from datetime import datetime, date

import db

log = logging.getLogger(__name__)
DB_PATH = "bsr_history.db"
_DAYS_PER_MONTH = 365.25 / 12.0   # 30.4375 — annualised daily rate for a monthly figure

VALID_KINDS = ("recurring", "oneoff")


def get_db(db_path=DB_PATH):
    conn = db.connect(db_path)
    if not db.is_postgres():
        conn.execute("PRAGMA journal_mode=WAL")
    return conn


def _now():
    return datetime.utcnow().isoformat()


def init_expenses_schema(db_path=DB_PATH):
    conn = get_db(db_path)
    pg = db.is_postgres()
    MONEY = "NUMERIC(14,4)" if pg else "REAL"
    IDCOL = ("BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY"
             if pg else "INTEGER PRIMARY KEY AUTOINCREMENT")
    conn.execute(f"""
        CREATE TABLE IF NOT EXISTS pl_overheads (
            id          {IDCOL},
            account_id  TEXT NOT NULL,          -- 'M4Mart_UK' | second account | 'shared'
            kind        TEXT NOT NULL,          -- 'recurring' | 'oneoff'
            frequency   TEXT,                   -- recurring: 'monthly' | 'weekly'  (NULL for oneoff)
            category    TEXT NOT NULL,          -- rent, labour, utilities, software, packaging, ...
            amount      {MONEY} NOT NULL,       -- recurring: PER month/week; oneoff: the whole cost
            start_date  TEXT,                   -- recurring: first active date (YYYY-MM-DD)
            end_date    TEXT,                   -- recurring: last active date (NULL = ongoing)
            on_date     TEXT,                   -- oneoff: the date it hit (YYYY-MM-DD)
            note        TEXT,
            created_at  TEXT NOT NULL
        )
    """)
    # additive migration: frequency column; existing recurring rows are monthly.
    if not _has_col(conn, "pl_overheads", "frequency"):
        conn.execute("ALTER TABLE pl_overheads ADD COLUMN frequency TEXT")
    conn.execute("UPDATE pl_overheads SET frequency='monthly' WHERE kind='recurring' AND (frequency IS NULL OR frequency='')")
    conn.execute("CREATE INDEX IF NOT EXISTS idx_overheads_acct ON pl_overheads(account_id, kind)")
    conn.commit()
    conn.close()
    log.info("Overheads schema initialised.")


def _has_col(conn, table, col):
    if db.is_postgres():
        return conn.execute(
            "SELECT 1 FROM information_schema.columns WHERE table_name=? AND column_name=?",
            (table, col)).fetchone() is not None
    rows = conn.execute(f"PRAGMA table_info({table})").fetchall()
    return any((r["name"] if not isinstance(r, (tuple, list)) else r[1]) == col for r in rows)


# ── CRUD ─────────────────────────────────────────────────────────────────────

VALID_FREQ = ("monthly", "weekly")


def add_overhead(account_id, kind, category, amount, start_date=None, end_date=None,
                 on_date=None, note=None, frequency=None, db_path=DB_PATH):
    if kind not in VALID_KINDS:
        raise ValueError(f"kind must be one of {VALID_KINDS}")
    if not category or not str(category).strip():
        raise ValueError("category is required")
    amount = float(amount)
    if kind == "recurring":
        frequency = (frequency or "monthly").lower()
        if frequency not in VALID_FREQ:
            raise ValueError(f"frequency must be one of {VALID_FREQ}")
        if not start_date:
            raise ValueError("recurring overhead needs a start date")
    else:
        frequency = None
        if not on_date:
            raise ValueError("one-off expense needs a date")
    conn = get_db(db_path)
    conn.execute(
        "INSERT INTO pl_overheads (account_id, kind, frequency, category, amount, start_date, "
        "end_date, on_date, note, created_at) VALUES (?,?,?,?,?,?,?,?,?,?)",
        (account_id, kind, frequency, category.strip(), amount,
         (start_date or None) if kind == "recurring" else None,
         (end_date or None) if kind == "recurring" else None,
         (on_date or None) if kind == "oneoff" else None,
         (note or None), _now()))
    conn.commit()
    conn.close()


def set_end_date(overhead_id, end_date, db_path=DB_PATH):
    """End-date a recurring overhead (e.g. rent changed) without deleting its history."""
    conn = get_db(db_path)
    conn.execute("UPDATE pl_overheads SET end_date=? WHERE id=? AND kind='recurring'",
                 ((end_date or None), overhead_id))
    conn.commit()
    conn.close()


def delete_overhead(overhead_id, db_path=DB_PATH):
    conn = get_db(db_path)
    conn.execute("DELETE FROM pl_overheads WHERE id=?", (overhead_id,))
    conn.commit()
    conn.close()


def list_overheads(account_id=None, db_path=DB_PATH):
    conn = get_db(db_path)
    if account_id and account_id != "all":
        rows = conn.execute(
            "SELECT * FROM pl_overheads WHERE account_id IN (?, 'shared') "
            "ORDER BY kind, category", (account_id,)).fetchall()
    else:
        rows = conn.execute(
            "SELECT * FROM pl_overheads ORDER BY kind, category").fetchall()
    conn.close()
    return [dict(r) for r in rows]


# ── period pro-ration (business-wide bottom line only) ───────────────────────

def _d(s):
    if not s:
        return None
    try:
        return datetime.strptime(str(s)[:10], "%Y-%m-%d").date()
    except ValueError:
        return None


def compute_overheads(account_id, start_date, end_date, db_path=DB_PATH):
    """Total overheads attributable to the viewed period [start_date, end_date]
    (inclusive ISO dates). Recurring lines are pro-rated by active days
    (monthly ÷ 30.4375 × days); one-offs count in full if dated in-window.
    account_id: a specific account includes that account's rows + 'shared'; 'all'
    (or None) includes everything. Returns
    {total, recurring, oneoff, days, lines:[{...per-line period amount...}]}."""
    s, e = _d(start_date), _d(end_date)
    if not s or not e or e < s:
        return {"total": 0.0, "recurring": 0.0, "oneoff": 0.0, "days": 0, "lines": []}

    rows = list_overheads(account_id, db_path=db_path)
    recurring_total = oneoff_total = 0.0
    lines = []
    for r in rows:
        amt = float(r["amount"] or 0)
        if r["kind"] == "recurring":
            rs = _d(r["start_date"]) or s
            re_ = _d(r["end_date"]) or e
            a_start = max(s, rs)
            a_end = min(e, re_)
            if a_end < a_start:
                continue
            days = (a_end - a_start).days + 1
            per_day = amt / (7.0 if r.get("frequency") == "weekly" else _DAYS_PER_MONTH)
            period_amt = round(per_day * days, 2)
            if period_amt <= 0:
                continue
            recurring_total += period_amt
            lines.append({"id": r["id"], "kind": "recurring",
                          "frequency": r.get("frequency") or "monthly",
                          "category": r["category"], "account_id": r["account_id"],
                          "amount": round(amt, 2), "monthly": round(amt, 2),
                          "period_amount": period_amt, "active_days": days,
                          "note": r.get("note")})
        else:  # oneoff
            od = _d(r["on_date"])
            if od and s <= od <= e:
                oneoff_total += amt
                lines.append({"id": r["id"], "kind": "oneoff", "category": r["category"],
                              "account_id": r["account_id"], "monthly": None,
                              "period_amount": round(amt, 2), "on_date": r["on_date"],
                              "note": r.get("note")})
    total = round(recurring_total + oneoff_total, 2)
    lines.sort(key=lambda x: -x["period_amount"])
    return {"total": total, "recurring": round(recurring_total, 2),
            "oneoff": round(oneoff_total, 2), "days": (e - s).days + 1, "lines": lines}


def overhead_baseline_trailing(account_id=None, months=3, as_of=None, db_path=DB_PATH):
    """STABLE overhead baseline over the last `months` COMPLETE calendar months (the
    in-progress month is EXCLUDED so nothing spikes at the start of a month or drifts as
    it fills in). Returns a dict:
        {months, start, end, overhead_total, revenue_total, rate,
         overhead_monthly, revenue_monthly}
    where rate = overhead £ per £1 of ex-VAT sales. Used two ways: `rate` drives the
    full-absorption REFERENCE layer, and the monthly figures drive the business-level
    overhead-coverage GOAL on /pl (overhead isn't baked into the per-unit target)."""
    from datetime import timedelta
    import pl_db
    ref = as_of or date.today()
    if isinstance(ref, datetime):
        ref = ref.date()
    first_this = ref.replace(day=1)
    end_prev = first_this - timedelta(days=1)              # last day of previous month
    y, m = first_this.year, first_this.month - months
    while m <= 0:
        m += 12
        y -= 1
    start_iso = date(y, m, 1).strftime("%Y-%m-01")
    end_iso = end_prev.strftime("%Y-%m-%dT23:59:59Z")      # inclusive of the whole day
    oh = (compute_overheads(account_id, start_iso, end_iso, db_path=db_path).get("total", 0.0) or 0.0)
    rev = pl_db.get_total_revenue(account_id, start_date=start_iso, end_date=end_iso) or 0.0
    return {"months": months, "start": start_iso, "end": end_iso,
            "overhead_total": oh, "revenue_total": rev,
            "rate": (oh / rev) if rev else 0.0,
            "overhead_monthly": oh / months if months else 0.0,
            "revenue_monthly": rev / months if months else 0.0}


def overhead_rate_trailing(account_id=None, months=3, as_of=None, db_path=DB_PATH):
    """Just the stable overhead-to-revenue rate (see overhead_baseline_trailing)."""
    return overhead_baseline_trailing(account_id, months=months, as_of=as_of, db_path=db_path)["rate"]


def monthly_equiv(amount, frequency):
    """A weekly figure expressed as a monthly run-rate (× 52/12); monthly stays as-is."""
    amount = float(amount or 0)
    return amount * (52.0 / 12.0) if frequency == "weekly" else amount


def monthly_run_rate(rows, today=None):
    """Sum of currently-active recurring overheads as a monthly figure (weekly → ×52/12)."""
    d = (today or date.today().isoformat())[:10]
    tot = 0.0
    for r in rows:
        if r["kind"] != "recurring":
            continue
        if r["end_date"] and str(r["end_date"])[:10] < d:
            continue
        tot += monthly_equiv(r["amount"], r.get("frequency"))
    return round(tot, 2)


def to_date(row, today=None):
    """Cumulative cost of a recurring row from its start to today (or its end date if
    earlier) — so the page can show that it really has accrued every month/week."""
    s = _d(row.get("start_date"))
    if not s:
        return 0.0
    e = _d(today) or date.today()
    end = _d(row.get("end_date"))
    if end and end < e:
        e = end
    if e < s:
        return 0.0
    days = (e - s).days + 1
    per_day = float(row["amount"] or 0) / (7.0 if row.get("frequency") == "weekly" else _DAYS_PER_MONTH)
    return round(per_day * days, 2)


# ── one-time migration: legacy flat overhead (pl_cogs.cogs_overheads) → recurring ──

def _table_exists(conn, table):
    if db.is_postgres():
        row = conn.execute(
            "SELECT 1 FROM information_schema.tables WHERE table_name=?", (table,)).fetchone()
        return row is not None
    row = conn.execute(
        "SELECT 1 FROM sqlite_master WHERE type='table' AND name=?", (table,)).fetchone()
    return row is not None


def _legacy_start_date(account_id, db_path):
    """Best start date for a migrated overhead: the account's earliest settled order
    (so it applies across the same history the old flat cost implicitly did); falls
    back to 12 months ago (first of month) if the P&L range isn't available."""
    try:
        import pl_db
        rs, _ = pl_db.resolve_pl_date_range(account_id)
        if rs:
            return str(rs)[:10]
    except Exception:
        pass
    d = date.today()
    return date(d.year - 1, d.month, 1).isoformat()


def migrate_flat_overheads_from_cogs(db_path=DB_PATH):
    """ONE-TIME: copy any legacy flat monthly overhead (cogs_overheads) into
    pl_overheads as a recurring row, then zero the legacy value so it can't re-run
    or double-count. Idempotent: a zeroed/absent legacy value is skipped, and an
    account that already has its own recurring overhead is not given a duplicate
    (its legacy value is still retired). Returns the number of rows migrated."""
    conn = get_db(db_path)
    if not _table_exists(conn, "cogs_overheads"):
        conn.close()
        return 0
    try:
        rows = conn.execute(
            "SELECT account_id, monthly_amount_exvat FROM cogs_overheads "
            "WHERE monthly_amount_exvat > 0").fetchall()
        legacy = [(r["account_id"], float(r["monthly_amount_exvat"] or 0)) for r in rows]
        # accounts that already have their OWN recurring overhead (not 'shared')
        have = {r["account_id"] for r in conn.execute(
            "SELECT DISTINCT account_id FROM pl_overheads WHERE kind='recurring'").fetchall()}
    except Exception:
        conn.close()
        return 0
    conn.close()

    migrated = 0
    for account_id, amount in legacy:
        if amount <= 0:
            continue
        if account_id not in have:
            add_overhead(
                account_id, "recurring", "General overheads (migrated)", amount,
                start_date=_legacy_start_date(account_id, db_path),
                note="Imported from the retired flat monthly-overhead field. "
                     "Adjust the start date or split into categories (rent/labour/…) if you like.",
                db_path=db_path)
            migrated += 1
        # retire the legacy value regardless, so it can never double-count or re-run
        c2 = get_db(db_path)
        c2.execute("UPDATE cogs_overheads SET monthly_amount_exvat=0, updated_at=? "
                   "WHERE account_id=?", (_now(), account_id))
        c2.commit()
        c2.close()
    if migrated:
        log.info("Migrated %d legacy flat overhead(s) into pl_overheads.", migrated)
    return migrated
