"""pl_ppc.py — Module 3 (PPC Ad Optimiser) data layer.

Phase A: ingest the Sponsored Products **Search Term** report (manual CSV, one per
account) at its native HOUR grain, so ads can be managed by day AND time of day.
The rule engine (dead-term negatives, harvesting, bid moves) is deferred — this
file first gets ALL the data in, cleanly, and provides read aggregations for the
dashboard's tables and day/hour graphs.

Dual-backend via db.py (SQLite locally, Postgres on Railway). Money is NUMERIC(14,4)
on PG / REAL on SQLite; timestamps are TEXT — same conventions as Module 2. These
tables are NEW (not part of the SQLite->PG migration), so init_ppc_schema() creates
them on BOTH backends (it does not skip on Postgres the way the migrated pl_* tables do).
"""
import os
import re
import csv
import json
import logging
from datetime import datetime, timezone, timedelta

import db

log = logging.getLogger(__name__)
DB_PATH = "bsr_history.db"   # same database as Modules 1 & 2


def _now():
    return datetime.now(timezone.utc).isoformat()


def get_db(db_path=DB_PATH):
    conn = db.connect(db_path)
    if not db.is_postgres():
        conn.execute("PRAGMA journal_mode=WAL")
    return conn


# ─────────────────────────────────────────────────────────────────────────────
# SCHEMA — 5 tables (Phase A populates ppc_search_terms; the rest are scaffolded
# now so Phases B/C don't need a schema rework). All carry account_id; a `channel`
# column is reserved for future multi-channel.
# ─────────────────────────────────────────────────────────────────────────────

def _column_exists(conn, table, col):
    """True if `col` is present on `table`, on either backend (used for additive,
    idempotent migrations without a bare ALTER that would abort a PG transaction)."""
    if db.is_postgres():
        row = conn.execute(
            "SELECT 1 FROM information_schema.columns WHERE table_name=? AND column_name=?",
            (table, col)).fetchone()
        return row is not None
    rows = conn.execute(f"PRAGMA table_info({table})").fetchall()
    return any((r["name"] if not isinstance(r, (tuple, list)) else r[1]) == col for r in rows)


def init_ppc_schema(db_path=DB_PATH):
    conn = get_db(db_path)
    pg = db.is_postgres()
    MONEY = "NUMERIC(14,4)" if pg else "REAL"
    IDCOL = ("BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY"
             if pg else "INTEGER PRIMARY KEY AUTOINCREMENT")

    # ppc_search_terms DDL is shared between fresh-create and the target-grain rebuild
    # migration (below), so the two never drift. The PK carries target_id so a search
    # term that matches more than one target in the same hour/ad-group can't collide
    # (that collision would silently drop a target's clicks and corrupt the rules).
    ST_DDL = f"""
        CREATE TABLE IF NOT EXISTS ppc_search_terms (
            account_id        TEXT NOT NULL,
            channel           TEXT NOT NULL DEFAULT 'amazon',
            ads_account_id    TEXT,
            portfolio_id      TEXT,
            portfolio_name    TEXT,
            campaign_id       TEXT NOT NULL,
            campaign_name     TEXT,
            ad_group_id       TEXT NOT NULL,
            ad_group_name     TEXT,
            search_term       TEXT NOT NULL,
            targeting_type    TEXT,            -- 'keyword' | 'product' (ASIN) | 'other'
            advertised_sku    TEXT NOT NULL DEFAULT '',
            target_id         TEXT NOT NULL DEFAULT '',   -- Ads 'Target ID' (keyword/target/auto-expression)
            target_bid        {MONEY},                    -- current 'Target bid'
            target_type       TEXT,                       -- report 'Target type' (e.g. rsf)
            match_type_raw    TEXT,                       -- 'Targeting match type': EXACT/BROAD/PHRASE (manual)
                                                          --   | TARGETING_EXPRESSION_PREDEFINED (auto) | TARGETING_EXPRESSION
            advertised_product_id TEXT,                   -- 'Advertised product ID' (ASIN)
            date              TEXT NOT NULL,   -- YYYY-MM-DD
            hour              INTEGER NOT NULL DEFAULT -1,   -- 0..23, -1 = day-level row
            day_of_week       TEXT,
            week              INTEGER,
            impressions       INTEGER NOT NULL DEFAULT 0,
            clicks            INTEGER NOT NULL DEFAULT 0,
            spend             {MONEY} NOT NULL DEFAULT 0,
            orders            INTEGER NOT NULL DEFAULT 0,
            sales             {MONEY} NOT NULL DEFAULT 0,
            units             INTEGER NOT NULL DEFAULT 0,
            sales_promoted    {MONEY} NOT NULL DEFAULT 0,
            sales_halo        {MONEY} NOT NULL DEFAULT 0,
            imported_at       TEXT NOT NULL,
            PRIMARY KEY (account_id, campaign_id, ad_group_id, target_id, search_term, advertised_sku, date, hour)
        )
        """

    stmts = [
        ST_DDL,
        # manual-campaign keywords with current bid (Phase B bid moves apply here only)
        f"""
        CREATE TABLE IF NOT EXISTS ppc_keywords (
            account_id     TEXT NOT NULL,
            campaign_id    TEXT NOT NULL,
            ad_group_id    TEXT NOT NULL,
            keyword        TEXT NOT NULL,
            match_type     TEXT,              -- broad | phrase | exact | product
            current_bid    {MONEY},
            updated_at     TEXT,
            PRIMARY KEY (account_id, campaign_id, ad_group_id, keyword, match_type)
        )
        """,
        # every term ever harvested — the harvest-tracking dedup
        f"""
        CREATE TABLE IF NOT EXISTS ppc_harvest_log (
            id             {IDCOL},
            account_id     TEXT NOT NULL,
            source_campaign TEXT,
            term           TEXT NOT NULL,
            target_campaign TEXT,
            harvested_at   TEXT NOT NULL
        )
        """,
        # every negative ever added — powers the negative-conflict guard
        f"""
        CREATE TABLE IF NOT EXISTS ppc_negative_log (
            id             {IDCOL},
            account_id     TEXT NOT NULL,
            campaign_id    TEXT NOT NULL,
            term_or_asin   TEXT NOT NULL,
            match_type     TEXT,              -- phrase | exact | product
            added_at       TEXT NOT NULL
        )
        """,
        # the worklist (populated once rules are set)
        f"""
        CREATE TABLE IF NOT EXISTS ppc_recommendations (
            id             {IDCOL},
            account_id     TEXT NOT NULL,
            rec_type       TEXT NOT NULL,     -- pause|harvest|negative|bid_up|bid_down|manual_review
            target         TEXT,
            rationale      TEXT,
            evidence_json  TEXT,
            status         TEXT NOT NULL DEFAULT 'pending',  -- pending|approved|rejected|executed
            decided_by     TEXT,
            decided_at     TEXT,
            created_at     TEXT NOT NULL
        )
        """,
        # Phase C — per-campaign day-parting schedule. active=1 means the hourly
        # scheduler manages this campaign's on/off. The simple daily ON window is
        # [on_start_hour, on_end_hour); hour_mask (24 chars of '1'/'0') is the
        # optional per-hour override that takes precedence when set (Phase: later).
        f"""
        CREATE TABLE IF NOT EXISTS ppc_campaign_schedule (
            account_id        TEXT NOT NULL,
            campaign_id       TEXT NOT NULL,
            campaign_name     TEXT,
            active            INTEGER NOT NULL DEFAULT 0,
            on_start_hour     INTEGER NOT NULL DEFAULT 0,
            on_end_hour       INTEGER NOT NULL DEFAULT 24,
            hour_mask         TEXT,
            last_desired_state TEXT,
            last_synced_at    TEXT,
            updated_at        TEXT,
            PRIMARY KEY (account_id, campaign_id)
        )
        """,
        # every enable/pause the scheduler (or a manual test) attempts, logged.
        f"""
        CREATE TABLE IF NOT EXISTS ppc_action_log (
            id             {IDCOL},
            account_id     TEXT NOT NULL,
            campaign_id    TEXT,
            campaign_name  TEXT,
            action         TEXT,              -- 'enable' | 'pause'
            desired_state  TEXT,              -- 'enabled' | 'paused'
            result         TEXT,              -- 'ok' | 'error' | 'dry_run' | 'noop'
            detail         TEXT,
            at             TEXT NOT NULL
        )
        """,
    ]
    for s in stmts:
        conn.execute(s)
    # additive migration: temporary-pause ("snooze until") timestamp on a campaign
    # schedule. When set and in the future, the reconciler forces the campaign paused
    # regardless of its day-parting window, then clears it on expiry (auto-resume).
    # Existence-checked (not a bare ALTER) so a duplicate doesn't poison the PG txn.
    if not _column_exists(conn, "ppc_campaign_schedule", "paused_until"):
        conn.execute("ALTER TABLE ppc_campaign_schedule ADD COLUMN paused_until TEXT")
    # target-grain migration: older ppc_search_terms had no target_id (and thus a PK
    # that could collide two targets in one hour). Rebuild it to the shared ST_DDL,
    # carrying old rows over with empty target/bid fields. Only runs once.
    if not _column_exists(conn, "ppc_search_terms", "target_id"):
        conn.execute("ALTER TABLE ppc_search_terms RENAME TO ppc_search_terms_old")
        conn.execute(ST_DDL)
        conn.execute("""
            INSERT INTO ppc_search_terms
                (account_id, channel, ads_account_id, portfolio_id, portfolio_name,
                 campaign_id, campaign_name, ad_group_id, ad_group_name, search_term,
                 targeting_type, advertised_sku, target_id, target_bid, target_type,
                 match_type_raw, advertised_product_id, date, hour, day_of_week, week,
                 impressions, clicks, spend, orders, sales, units, sales_promoted,
                 sales_halo, imported_at)
            SELECT account_id, channel, ads_account_id, portfolio_id, portfolio_name,
                   campaign_id, campaign_name, ad_group_id, ad_group_name, search_term,
                   targeting_type, advertised_sku, '', NULL, NULL,
                   NULL, NULL, date, hour, day_of_week, week,
                   impressions, clicks, spend, orders, sales, units, sales_promoted,
                   sales_halo, imported_at
            FROM ppc_search_terms_old
        """)
        conn.execute("DROP TABLE ppc_search_terms_old")
        log.info("ppc_search_terms rebuilt at target grain (target_id added to PK).")
    # helpful indexes for the dashboard aggregations
    for idx in [
        "CREATE INDEX IF NOT EXISTS idx_ppc_st_acct_date ON ppc_search_terms(account_id, date)",
        "CREATE INDEX IF NOT EXISTS idx_ppc_st_campaign ON ppc_search_terms(account_id, campaign_id)",
        "CREATE INDEX IF NOT EXISTS idx_ppc_st_term ON ppc_search_terms(account_id, search_term)",
    ]:
        conn.execute(idx)
    conn.commit()
    conn.close()
    log.info("Module 3 (PPC) schema initialised.")


# ─────────────────────────────────────────────────────────────────────────────
# IMPORT — Sponsored Products "Search Term" report CSV
# ─────────────────────────────────────────────────────────────────────────────

def _unesc(v):
    """Amazon exports IDs Excel-escaped as  ="12345"  to stop Excel eating leading
    zeros / converting to scientific notation. Strip that wrapper."""
    if v is None:
        return None
    v = v.strip()
    m = re.match(r'^="?(.*?)"?$', v)
    if v.startswith('="') and v.endswith('"'):
        return v[2:-1]
    return v


def _num(v, cast=float):
    """Parse a numeric cell: drop %, £, commas, blanks -> 0."""
    if v is None:
        return cast(0)
    s = str(v).strip().replace("£", "").replace(",", "").replace("%", "")
    if s in ("", "-", "--"):
        return cast(0)
    try:
        return cast(float(s))
    except (ValueError, TypeError):
        return cast(0)


_DATE_FORMATS = ("%b %d, %Y", "%Y-%m-%d", "%d/%m/%Y", "%m/%d/%Y", "%d %b %Y")


def _parse_date(v):
    """'Jul 29, 2026' (this report's format) -> '2026-07-29'. Tolerant of a few
    other spellings so a re-export in a different locale still lands."""
    if not v:
        return None
    s = str(v).strip()
    for fmt in _DATE_FORMATS:
        try:
            return datetime.strptime(s, fmt).strftime("%Y-%m-%d")
        except ValueError:
            continue
    return s   # last resort: store as-is rather than drop the row


_ASIN_RE = re.compile(r"^B0[A-Z0-9]{8}$", re.IGNORECASE)


def _targeting_type(search_term):
    st = (search_term or "").strip()
    if _ASIN_RE.match(st):
        return "product"          # ASIN / product-targeting term
    if st.startswith("b0") and len(st) == 10:
        return "product"
    return "keyword"


def _norm(h):
    return re.sub(r"[^a-z0-9]+", " ", (h or "").lower()).strip()


def _resolve_headers(fieldnames):
    """Map our field names -> the report's real header strings (normalised match),
    tolerant of the BOM on the first column and minor wording drift."""
    norm_to_real = {}
    for h in fieldnames or []:
        norm_to_real.setdefault(_norm(h), h)

    def find(*exacts):
        for e in exacts:
            if _norm(e) in norm_to_real:
                return norm_to_real[_norm(e)]
        return None

    return {
        "ads_account_id": find("Advertiser account ID"),
        "portfolio_id":   find("Portfolio ID"),
        "portfolio_name": find("Portfolio name"),
        "campaign_id":    find("Campaign ID"),
        "campaign_name":  find("Campaign name"),
        "ad_group_id":    find("Ad group ID"),
        "ad_group_name":  find("Ad group name"),
        "search_term":    find("Search term", "Customer Search Term"),
        "hour":           find("Hour"),
        "day_of_week":    find("Day of week"),
        "week":           find("Week"),
        "date":           find("Date"),
        "sku":            find("Advertised product SKU", "SKU"),
        "target_id":      find("Target ID"),
        "target_bid":     find("Target bid"),
        "target_type":    find("Target type"),
        "match_type_raw": find("Targeting match type", "Match type"),
        "advertised_product_id": find("Advertised product ID", "ASIN"),
        "impressions":    find("Impressions"),
        "clicks":         find("Clicks"),
        "spend":          find("Total cost", "Spend", "Cost"),
        "orders":         find("Purchases", "7 Day Total Orders (#)", "Orders"),
        "sales":          find("Sales", "7 Day Total Sales"),
        "units":          find("Units sold", "7 Day Total Units (#)", "Units"),
        "sales_promoted": find("Sales (promoted)"),
        "sales_halo":     find("Sales (halo)"),
    }


def import_search_term_csv(account_id, path, db_path=DB_PATH):
    """Parse a Search Term report CSV and upsert into ppc_search_terms at the hour
    grain. Re-uploading a wider date range is safe (upsert, not append). Returns
    a dict summary: {rows, inserted_or_updated, date_min, date_max, hours, skipped}."""
    conn = get_db(db_path)
    with open(path, newline="", encoding="utf-8-sig") as f:
        reader = csv.DictReader(f)
        cols = _resolve_headers(reader.fieldnames)
        if not cols["search_term"] or not cols["campaign_id"] or not cols["date"]:
            conn.close()
            raise ValueError("This does not look like a Search Term report — missing "
                             "'Search term', 'Campaign ID' or 'Date'. (The Advertised "
                             "Product report has no search-term column — use the "
                             "Sponsored Products → Search Term report.)")
        n = 0
        skipped = 0
        dmin, dmax = None, None
        hours = set()
        now = _now()

        def g(row, key):
            h = cols.get(key)
            return row.get(h) if h else None

        for row in reader:
            st = (g(row, "search_term") or "").strip()
            date = _parse_date(g(row, "date"))
            camp_id = _unesc(g(row, "campaign_id"))
            if not st or not date or not camp_id:
                skipped += 1
                continue
            hour = int(_num(g(row, "hour"), int)) if cols.get("hour") else -1
            sku = (g(row, "sku") or "").strip()
            target_id = (_unesc(g(row, "target_id")) or "") if cols.get("target_id") else ""
            target_bid = _num(g(row, "target_bid")) if cols.get("target_bid") else None
            target_type = g(row, "target_type") if cols.get("target_type") else None
            match_raw = (g(row, "match_type_raw") or "").strip() or None
            adv_pid = _unesc(g(row, "advertised_product_id")) if cols.get("advertised_product_id") else None
            conn.execute("""
                INSERT INTO ppc_search_terms
                    (account_id, ads_account_id, portfolio_id, portfolio_name,
                     campaign_id, campaign_name, ad_group_id, ad_group_name,
                     search_term, targeting_type, advertised_sku, target_id, target_bid,
                     target_type, match_type_raw, advertised_product_id, date, hour,
                     day_of_week, week, impressions, clicks, spend, orders, sales,
                     units, sales_promoted, sales_halo, imported_at)
                VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)
                ON CONFLICT (account_id, campaign_id, ad_group_id, target_id, search_term, advertised_sku, date, hour)
                DO UPDATE SET
                    campaign_name=excluded.campaign_name, ad_group_name=excluded.ad_group_name,
                    targeting_type=excluded.targeting_type, target_bid=excluded.target_bid,
                    target_type=excluded.target_type, match_type_raw=excluded.match_type_raw,
                    advertised_product_id=excluded.advertised_product_id, day_of_week=excluded.day_of_week,
                    week=excluded.week, impressions=excluded.impressions, clicks=excluded.clicks,
                    spend=excluded.spend, orders=excluded.orders, sales=excluded.sales,
                    units=excluded.units, sales_promoted=excluded.sales_promoted,
                    sales_halo=excluded.sales_halo, imported_at=excluded.imported_at
            """, (
                account_id, _unesc(g(row, "ads_account_id")), _unesc(g(row, "portfolio_id")),
                g(row, "portfolio_name"), camp_id, g(row, "campaign_name"),
                _unesc(g(row, "ad_group_id")), g(row, "ad_group_name"),
                st, _targeting_type(st), sku, target_id, target_bid,
                target_type, match_raw, adv_pid, date, hour,
                g(row, "day_of_week"), int(_num(g(row, "week"), int)),
                int(_num(g(row, "impressions"), int)), int(_num(g(row, "clicks"), int)),
                _num(g(row, "spend")), int(_num(g(row, "orders"), int)), _num(g(row, "sales")),
                int(_num(g(row, "units"), int)), _num(g(row, "sales_promoted")),
                _num(g(row, "sales_halo")), now,
            ))
            n += 1
            hours.add(hour)
            dmin = date if dmin is None or date < dmin else dmin
            dmax = date if dmax is None or date > dmax else dmax
        conn.commit()
    conn.close()
    log.info(f"PPC Search Term import ({account_id}): {n} row(s) upserted, "
             f"{skipped} skipped, {dmin}..{dmax}.")
    recs = rebuild_recommendations(account_id, db_path=db_path)   # dry-run worklist
    return {"rows": n, "skipped": skipped, "date_min": dmin, "date_max": dmax,
            "hours": sorted(h for h in hours if h >= 0), "recs": recs}


# ─────────────────────────────────────────────────────────────────────────────
# READ AGGREGATIONS (for the dashboard tables + day/hour graphs)
# ─────────────────────────────────────────────────────────────────────────────

def _acct_where(account_id):
    if account_id and account_id != "all":
        return " WHERE account_id=?", [account_id]
    return "", []


def _filters(account_id=None, campaign_id=None, search_term=None):
    """Build a WHERE clause for the drill-downs: account + optional campaign +
    optional search term."""
    clauses, params = [], []
    if account_id and account_id != "all":
        clauses.append("account_id=?"); params.append(account_id)
    if campaign_id:
        clauses.append("campaign_id=?"); params.append(campaign_id)
    if search_term:
        clauses.append("search_term=?"); params.append(search_term)
    where = (" WHERE " + " AND ".join(clauses)) if clauses else ""
    return where, params


def get_totals(account_id="all", db_path=DB_PATH):
    conn = get_db(db_path)
    w, p = _acct_where(account_id)
    row = conn.execute(f"""
        SELECT COUNT(*) AS rows, COUNT(DISTINCT search_term) AS terms,
               COUNT(DISTINCT campaign_id) AS campaigns,
               SUM(impressions) AS impressions, SUM(clicks) AS clicks,
               ROUND(SUM(spend),2) AS spend, SUM(orders) AS orders,
               ROUND(SUM(sales),2) AS sales, MIN(date) AS date_min, MAX(date) AS date_max
        FROM ppc_search_terms{w}
    """, p).fetchone()
    conn.close()
    return dict(row) if row else {}


def by_day(account_id="all", campaign_id=None, search_term=None, db_path=DB_PATH):
    conn = get_db(db_path)
    w, p = _filters(account_id, campaign_id, search_term)
    rows = conn.execute(f"""
        SELECT date, SUM(impressions) AS impressions, SUM(clicks) AS clicks,
               ROUND(SUM(spend),2) AS spend, SUM(orders) AS orders, ROUND(SUM(sales),2) AS sales
        FROM ppc_search_terms{w}
        GROUP BY date ORDER BY date
    """, p).fetchall()
    conn.close()
    return [dict(r) for r in rows]


def by_hour(account_id="all", campaign_id=None, search_term=None, db_path=DB_PATH):
    """Hour-of-day breakdown (0..23). This is the day-parting view: where does
    spend convert vs waste, by time of day, optionally for one campaign or term."""
    conn = get_db(db_path)
    w, p = _filters(account_id, campaign_id, search_term)
    extra = (" AND hour >= 0") if w else (" WHERE hour >= 0")
    rows = conn.execute(f"""
        SELECT hour, SUM(impressions) AS impressions, SUM(clicks) AS clicks,
               ROUND(SUM(spend),2) AS spend, SUM(orders) AS orders, ROUND(SUM(sales),2) AS sales
        FROM ppc_search_terms{w}{extra}
        GROUP BY hour ORDER BY hour
    """, p).fetchall()
    conn.close()
    return [dict(r) for r in rows]


def entity_totals(account_id="all", campaign_id=None, search_term=None, db_path=DB_PATH):
    conn = get_db(db_path)
    w, p = _filters(account_id, campaign_id, search_term)
    row = conn.execute(f"""
        SELECT COUNT(DISTINCT search_term) AS terms, COUNT(DISTINCT campaign_id) AS campaigns,
               MAX(campaign_name) AS campaign_name,
               SUM(impressions) AS impressions, SUM(clicks) AS clicks,
               ROUND(SUM(spend),2) AS spend, SUM(orders) AS orders, ROUND(SUM(sales),2) AS sales,
               MIN(date) AS date_min, MAX(date) AS date_max
        FROM ppc_search_terms{w}
    """, p).fetchone()
    conn.close()
    return dict(row) if row else {}


def terms_for_campaign(account_id, campaign_id, limit=500, db_path=DB_PATH):
    conn = get_db(db_path)
    w, p = _filters(account_id, campaign_id)
    rows = conn.execute(f"""
        SELECT search_term, targeting_type, SUM(impressions) AS impressions, SUM(clicks) AS clicks,
               ROUND(SUM(spend),2) AS spend, SUM(orders) AS orders, ROUND(SUM(sales),2) AS sales
        FROM ppc_search_terms{w}
        GROUP BY search_term, targeting_type
        ORDER BY SUM(spend) DESC LIMIT {int(limit)}
    """, p).fetchall()
    conn.close()
    return [dict(r) for r in rows]


def campaigns_for_term(account_id, search_term, db_path=DB_PATH):
    conn = get_db(db_path)
    w, p = _filters(account_id, search_term=search_term)
    rows = conn.execute(f"""
        SELECT campaign_id, campaign_name, SUM(clicks) AS clicks,
               ROUND(SUM(spend),2) AS spend, SUM(orders) AS orders, ROUND(SUM(sales),2) AS sales
        FROM ppc_search_terms{w}
        GROUP BY campaign_id, campaign_name
        ORDER BY SUM(spend) DESC
    """, p).fetchall()
    conn.close()
    return [dict(r) for r in rows]


# ─────────────────────────────────────────────────────────────────────────────
# TACOS — ad spend ÷ settlement-anchored total revenue (Module 2). Account-level
# headline + per-ASIN. NOT per-search-term (TACOS is undefined at term grain —
# the search-term table keeps ACOS). Two clocks: ad spend is click-date, revenue
# is settlement-date. Gated on sync freshness so it isn't divided into frozen revenue.
# ─────────────────────────────────────────────────────────────────────────────

def _asin_maps(conn):
    """Shared SKU→ASIN mapping (+ a representative ASIN→SKU for display), built from
    your SKU→ASIN table (cogs_sku_asin) and Amazon's advertised (asin, sku) pairs,
    normalised for the two real-data quirks (HTML entities like 18&quot;X4 vs 18"X4;
    alias/separator diffs via cogs_aliases). Returns
    (canon_to_asin, sku_to_asin, canon_fn, asin_to_sku)."""
    import html as _html
    alias_map = {r["variant_sku"]: r["canonical_sku"]
                 for r in conn.execute("SELECT variant_sku, canonical_sku FROM cogs_aliases").fetchall()}

    def _canon(s):
        s = s or ""
        if s in alias_map:
            return alias_map[s]
        u = _html.unescape(s)
        return alias_map.get(u, u)

    canon_to_asin, sku_to_asin, asin_to_sku = {}, {}, {}

    def _reg_sku(asin, sku):
        if not asin or not sku:
            return
        cur = asin_to_sku.get(asin)
        if cur is None or len(sku) < len(cur):   # shortest = most 'canonical-looking'
            asin_to_sku[asin] = sku

    for r in conn.execute("SELECT variant_sku, asin FROM cogs_sku_asin").fetchall():
        canon_to_asin.setdefault(_canon(r["variant_sku"]), r["asin"])
        sku_to_asin.setdefault(_html.unescape(r["variant_sku"] or ""), r["asin"])
        _reg_sku(r["asin"], r["variant_sku"])
    for r in conn.execute("SELECT DISTINCT asin, sku FROM ad_spend WHERE sku IS NOT NULL AND sku!=''").fetchall():
        canon_to_asin.setdefault(_canon(r["sku"]), r["asin"])
        sku_to_asin.setdefault(_html.unescape(r["sku"] or ""), r["asin"])
        _reg_sku(r["asin"], r["sku"])
    return canon_to_asin, sku_to_asin, _canon, asin_to_sku


def get_tacos(account_id="all", db_path=DB_PATH):
    import pl_ads
    conn = get_db(db_path)
    try:
        row = conn.execute("SELECT MAX(latest_synced) AS m FROM pl_sync_state").fetchone()
        last_synced = row["m"] if row and row["m"] else None
    except Exception:
        last_synced = None
    conn.close()

    cov_min, cov_max = pl_ads.get_ad_data_coverage(account_id=account_id, db_path=db_path)
    if not cov_min:
        return {"has_ad": False}

    ad_by_asin = pl_ads.get_ad_spend_by_asin(account_id, cov_min, cov_max, db_path=db_path)
    total_spend = round(sum((v.get("spend") or 0) for v in ad_by_asin.values()), 2)

    import html as _html
    conn = get_db(db_path)
    acc = " AND account_id=?" if (account_id and account_id != "all") else ""
    ap = [account_id] if acc else []
    # total settled gross (ex-VAT) over the ad-coverage window — the TACOS denominator
    total_rev = conn.execute(
        f"SELECT ROUND(SUM(sale_price_exvat),2) AS r FROM pl_line_items "
        f"WHERE substr(posted_date,1,10) >= ? AND substr(posted_date,1,10) <= ?{acc}",
        (cov_min, cov_max, *ap)).fetchone()["r"] or 0.0

    # Build SKU/canonical -> ASIN maps (+ ASIN -> representative SKU for display),
    # normalised for two real-data quirks so the per-ASIN revenue join actually hits:
    # (1) pl_line_items.sku stores HTML entities (e.g. 18&quot;X4) vs decoded 18"X4;
    # (2) separators/aliases differ (BD-6372=P4 vs BD-6372-P4). See _asin_maps.
    canon_to_asin, sku_to_asin, _canon, asin_to_sku = _asin_maps(conn)

    rev_by_asin = {}
    for r in conn.execute(
            f"""SELECT canonical_sku, sku, SUM(sale_price_exvat) AS rev FROM pl_line_items
                WHERE substr(posted_date,1,10) >= ? AND substr(posted_date,1,10) <= ?{acc}
                GROUP BY canonical_sku, sku""", (cov_min, cov_max, *ap)).fetchall():
        a = canon_to_asin.get(r["canonical_sku"]) or sku_to_asin.get(_html.unescape(r["sku"] or ""))
        if a:
            rev_by_asin[a] = rev_by_asin.get(a, 0.0) + (r["rev"] or 0.0)
    conn.close()

    per_asin = []
    for asin, v in ad_by_asin.items():
        rev = rev_by_asin.get(asin, 0.0)
        spend = round(v.get("spend") or 0, 2)
        per_asin.append({
            "asin": asin, "sku": asin_to_sku.get(asin), "spend": spend,
            "ad_sales": round(v.get("ad_sales") or 0, 2),
            "revenue": rev, "tacos": (spend / rev) if rev else None})
    per_asin.sort(key=lambda x: -(x["spend"] or 0))

    account_tacos = (total_spend / total_rev) if total_rev else None
    # stale = revenue hasn't caught up to the ad window's end (frozen relative to spend)
    stale = (last_synced is None) or (str(last_synced)[:10] < cov_max)
    return {"has_ad": True, "cov_min": cov_min, "cov_max": cov_max,
            "total_spend": total_spend, "total_rev": total_rev,
            "account_tacos": account_tacos, "per_asin": per_asin,
            "last_synced": last_synced, "stale": stale}


def get_campaign_tacos(account_id="all", db_path=DB_PATH):
    """Per-campaign TACOS = campaign ad spend (Search Term report, click-date) ÷
    settled ex-VAT revenue of the ASIN(s) that campaign advertises (settlement-date,
    Module 2). Because several campaigns can advertise the same SKU, they share that
    SKU's revenue — so per-campaign TACOS does NOT sum to the account figure. It
    answers 'this campaign's spend vs the revenue of the product it promotes'.
    Returns {'by_id': {campaign_id: {spend, ad_sales, orders, revenue, tacos, asins}},
    'dmin', 'dmax'}. Spend/revenue windowed to the imported Search Term date range."""
    import html as _html
    conn = get_db(db_path)
    w, p = _acct_where(account_id)
    dr = conn.execute(f"SELECT MIN(date) AS mn, MAX(date) AS mx FROM ppc_search_terms{w}", p).fetchone()
    dmin = dr["mn"] if dr else None
    dmax = dr["mx"] if dr else None
    if not dmin:
        conn.close()
        return {"by_id": {}, "dmin": None, "dmax": None}

    rows = conn.execute(f"""
        SELECT campaign_id, campaign_name, advertised_sku,
               ROUND(SUM(spend),2) AS spend, ROUND(SUM(sales),2) AS ad_sales, SUM(orders) AS orders
        FROM ppc_search_terms{w}
        GROUP BY campaign_id, campaign_name, advertised_sku
    """, p).fetchall()

    canon_to_asin, sku_to_asin, _canon, _ = _asin_maps(conn)
    acc = " AND account_id=?" if (account_id and account_id != "all") else ""
    ap = [account_id] if acc else []
    rev_by_asin = {}
    for r in conn.execute(
            f"""SELECT canonical_sku, sku, SUM(sale_price_exvat) AS rev FROM pl_line_items
                WHERE substr(posted_date,1,10) >= ? AND substr(posted_date,1,10) <= ?{acc}
                GROUP BY canonical_sku, sku""", (dmin, dmax, *ap)).fetchall():
        a = canon_to_asin.get(r["canonical_sku"]) or sku_to_asin.get(_html.unescape(r["sku"] or ""))
        if a:
            rev_by_asin[a] = rev_by_asin.get(a, 0.0) + (r["rev"] or 0.0)
    conn.close()

    camp = {}
    for r in rows:
        cid = r["campaign_id"]
        c = camp.setdefault(cid, {"campaign_id": cid, "campaign_name": r["campaign_name"],
                                  "spend": 0.0, "ad_sales": 0.0, "orders": 0, "asins": set()})
        c["spend"] += r["spend"] or 0
        c["ad_sales"] += r["ad_sales"] or 0
        c["orders"] += r["orders"] or 0
        a = (canon_to_asin.get(_canon(r["advertised_sku"]))
             or sku_to_asin.get(_html.unescape(r["advertised_sku"] or "")))
        if a:
            c["asins"].add(a)

    by_id = {}
    for cid, c in camp.items():
        rev = round(sum(rev_by_asin.get(a, 0.0) for a in c["asins"]), 2)
        by_id[cid] = {"campaign_id": cid, "campaign_name": c["campaign_name"],
                      "spend": round(c["spend"], 2), "ad_sales": round(c["ad_sales"], 2),
                      "orders": c["orders"], "revenue": rev,
                      "tacos": (c["spend"] / rev) if rev else None,
                      "asins": sorted(c["asins"])}
    return {"by_id": by_id, "dmin": dmin, "dmax": dmax}


# ─────────────────────────────────────────────────────────────────────────────
# PHASE A — recommendation worklist (dry-run, no creds, no writes to Amazon)
# Aggregates the Search Term report ACROSS hour+day rows to a per (campaign, ad
# group, target, search term) grain BEFORE applying rules — otherwise one term
# spread over 13 hourly 1-click rows reads as thirteen 1-click terms and every
# suggestion is wrong. Match-type branches the ACTION: manual keywords (EXACT/
# BROAD/PHRASE) → pause/bid the keyword; auto (TARGETING_EXPRESSION_PREDEFINED) →
# add a negative exact (needs only campaign/ad-group).
# ─────────────────────────────────────────────────────────────────────────────

_MANUAL_MATCH = {"BROAD", "EXACT", "PHRASE"}
# rule thresholds (tuned so the sample report yields 1 pause / 4 review / 60 harvest;
# reasonable general defaults too)
PAUSE_MIN_CLICKS = 8       # manual keyword, 0 sales, this many clicks → confident pause
REVIEW_MIN_CLICKS = 5      # 0 sales, sub-threshold spend, this many clicks → human look
REVIEW_MAX_SPEND = 5.0     # £ — below the "confident pause" spend, so route to review
HARVEST_MIN_ORDERS = 1     # non-manual (auto/product) term with ≥ this many orders → harvest
BID_DOWN_ACOS = 0.50       # converting manual keyword above this ACOS → suggest a lower bid
BID_DOWN_FACTOR = 0.75     # suggested new bid = current × this (a 25% trim)
BID_FLOOR = 0.05           # never suggest below this


def _is_manual(match_raw):
    return (match_raw or "").strip().upper() in _MANUAL_MATCH


def rebuild_recommendations(account_id, db_path=DB_PATH):
    """Regenerate the pending worklist for an account from the imported Search Term
    data. Returns a dict of bucket counts. DRY-RUN ONLY — writes recommendation rows,
    never touches Amazon. Existing NON-pending (decided) recs are preserved."""
    conn = get_db(db_path)
    conn.execute("DELETE FROM ppc_recommendations WHERE account_id=? AND status='pending'",
                 (account_id,))
    # aggregate across hour + day to the term×target grain
    rows = conn.execute("""
        SELECT campaign_id, MAX(campaign_name) AS campaign_name,
               ad_group_id, MAX(ad_group_name) AS ad_group_name,
               target_id, COALESCE(match_type_raw,'') AS match_raw,
               search_term, MAX(targeting_type) AS targeting_type,
               MAX(advertised_sku) AS sku, MAX(advertised_product_id) AS asin,
               MAX(target_bid) AS target_bid,
               SUM(impressions) AS impressions, SUM(clicks) AS clicks,
               ROUND(SUM(spend),2) AS spend, SUM(orders) AS orders, ROUND(SUM(sales),2) AS sales
        FROM ppc_search_terms
        WHERE account_id=?
        GROUP BY campaign_id, ad_group_id, target_id, COALESCE(match_type_raw,''), search_term
    """, (account_id,)).fetchall()

    now = _now()
    counts = {"pause": 0, "manual_review": 0, "harvest": 0, "bid_down": 0}
    harvest_terms = {}   # dedup harvest by search term (sum across its non-manual targets)

    def _add(rec_type, target, rationale, ev):
        conn.execute("""INSERT INTO ppc_recommendations
            (account_id, rec_type, target, rationale, evidence_json, status, created_at)
            VALUES (?,?,?,?,?, 'pending', ?)""",
            (account_id, rec_type, target, rationale, json.dumps(ev), now))
        counts[rec_type] = counts.get(rec_type, 0) + 1

    for r in rows:
        r = dict(r)
        manual = _is_manual(r["match_raw"])
        clicks, spend, orders, sales = (r["clicks"] or 0), (r["spend"] or 0), (r["orders"] or 0), (r["sales"] or 0)
        ev = {"campaign_id": r["campaign_id"], "campaign_name": r["campaign_name"],
              "ad_group_id": r["ad_group_id"], "ad_group_name": r["ad_group_name"],
              "target_id": r["target_id"], "match_type": r["match_raw"],
              "search_term": r["search_term"], "sku": r["sku"], "asin": r["asin"],
              "clicks": clicks, "spend": round(spend, 2), "orders": orders, "sales": round(sales, 2),
              "acos": (round(spend / sales, 3) if sales else None),
              "current_bid": r["target_bid"],
              "action_hint": "keyword_pause" if manual else "negative_exact"}

        # 1) PAUSE — manual keyword, real click volume, zero sales
        if manual and orders == 0 and clicks >= PAUSE_MIN_CLICKS:
            _add("pause", r["search_term"],
                 f"Manual {r['match_raw']} keyword, {clicks} clicks / £{spend:.2f}, 0 sales — pause it.", ev)
        # 2) MANUAL REVIEW — zero sales, some spend but below the confident-pause bar
        elif orders == 0 and spend < REVIEW_MAX_SPEND and clicks >= REVIEW_MIN_CLICKS:
            hint = "negative_exact" if not manual else "keyword_pause"
            ev["action_hint"] = hint
            _add("manual_review", r["search_term"],
                 f"{clicks} clicks / £{spend:.2f}, 0 sales ({'auto→negative' if not manual else r['match_raw']+' keyword'}) — review.", ev)
        # 3) BID DOWN — converting manual keyword, but ACOS too high
        elif manual and orders >= 1 and sales > 0 and r["target_bid"] and (spend / sales) > BID_DOWN_ACOS:
            new_bid = max(BID_FLOOR, round((r["target_bid"] or 0) * BID_DOWN_FACTOR, 2))
            ev["suggested_bid"] = new_bid
            _add("bid_down", r["search_term"],
                 f"{r['match_raw']} keyword converts but ACOS {100*spend/sales:.0f}% — "
                 f"cut bid £{r['target_bid']:.2f} → £{new_bid:.2f}.", ev)

        # HARVEST — non-manual (auto/product) converting term, deduped by search term
        if not manual and orders >= HARVEST_MIN_ORDERS:
            h = harvest_terms.setdefault(r["search_term"],
                {"clicks": 0, "spend": 0.0, "orders": 0, "sales": 0.0, "asin": r["asin"],
                 "campaign_id": r["campaign_id"], "campaign_name": r["campaign_name"],
                 "ad_group_id": r["ad_group_id"]})
            h["clicks"] += clicks; h["spend"] += spend; h["orders"] += orders; h["sales"] += sales

    for term, h in harvest_terms.items():
        ev = {"search_term": term, "clicks": h["clicks"], "spend": round(h["spend"], 2),
              "orders": h["orders"], "sales": round(h["sales"], 2),
              "acos": (round(h["spend"] / h["sales"], 3) if h["sales"] else None),
              "asin": h["asin"], "campaign_id": h["campaign_id"],
              "campaign_name": h["campaign_name"], "ad_group_id": h["ad_group_id"],
              "action_hint": "harvest_exact"}
        _add("harvest", term,
             f"Converting term ({h['orders']} order(s) / £{h['sales']:.2f}) from auto/product "
             f"targeting — add as its own exact keyword.", ev)

    conn.commit()
    conn.close()
    log.info("PPC recommendations rebuilt (%s): %s", account_id, counts)
    return counts


def get_recommendations(account_id="all", rec_type=None, status="pending", db_path=DB_PATH):
    conn = get_db(db_path)
    clauses, params = [], []
    if account_id and account_id != "all":
        clauses.append("account_id=?"); params.append(account_id)
    if rec_type:
        clauses.append("rec_type=?"); params.append(rec_type)
    if status:
        clauses.append("status=?"); params.append(status)
    where = (" WHERE " + " AND ".join(clauses)) if clauses else ""
    rows = conn.execute(
        f"SELECT * FROM ppc_recommendations{where} ORDER BY rec_type, id", params).fetchall()
    conn.close()
    out = []
    for r in rows:
        d = dict(r)
        try:
            d["evidence"] = json.loads(d.get("evidence_json") or "{}")
        except Exception:
            d["evidence"] = {}
        out.append(d)
    return out


def recommendation_counts(account_id="all", status="pending", db_path=DB_PATH):
    conn = get_db(db_path)
    clauses, params = [], []
    if account_id and account_id != "all":
        clauses.append("account_id=?"); params.append(account_id)
    if status:
        clauses.append("status=?"); params.append(status)
    where = (" WHERE " + " AND ".join(clauses)) if clauses else ""
    rows = conn.execute(
        f"SELECT rec_type, COUNT(*) AS n FROM ppc_recommendations{where} GROUP BY rec_type",
        params).fetchall()
    conn.close()
    return {r["rec_type"]: r["n"] for r in rows}


# ─────────────────────────────────────────────────────────────────────────────
# PHASE C — day-parting schedule + action log
# ─────────────────────────────────────────────────────────────────────────────

def desired_state_for_hour(sched, hour):
    """'enabled' or 'paused' for a schedule row at a given hour (0-23). A 24-char
    hour_mask ('1'=on) overrides the simple [on_start_hour, on_end_hour) window;
    the window may wrap midnight (start > end)."""
    mask = (sched.get("hour_mask") or "").strip()
    if len(mask) == 24:
        return "enabled" if mask[hour] == "1" else "paused"
    s = int(sched.get("on_start_hour") or 0)
    e = int(sched.get("on_end_hour") if sched.get("on_end_hour") is not None else 24)
    if s <= e:
        on = (s <= hour < e)
    else:  # wraps midnight, e.g. 22:00 -> 06:00
        on = (hour >= s or hour < e)
    return "enabled" if on else "paused"


def _parse_iso(s):
    if not s:
        return None
    try:
        return datetime.fromisoformat(str(s))
    except Exception:
        return None


def is_snoozed(sched, now_dt=None):
    """True while a temporary pause is in effect (paused_until in the future)."""
    pu = _parse_iso(sched.get("paused_until"))
    if not pu:
        return False
    now_dt = now_dt or datetime.now(timezone.utc)
    if pu.tzinfo is None:
        pu = pu.replace(tzinfo=timezone.utc)
    if now_dt.tzinfo is None:
        now_dt = now_dt.replace(tzinfo=timezone.utc)
    return pu > now_dt


def desired_state_now(sched, now_hour, now_dt=None):
    """The state a campaign should be in RIGHT NOW. A temporary pause (snooze)
    overrides everything; otherwise the day-parting window if the schedule is active;
    otherwise 'enabled' — which is only ever applied to resume a snoozed campaign that
    isn't on the auto-schedule (a plain untracked campaign is never touched: see the
    reconciler, which skips rows that are neither active nor snoozed)."""
    if is_snoozed(sched, now_dt):
        return "paused"
    if sched.get("active"):
        return desired_state_for_hour(sched, now_hour)
    return "enabled"


def snooze_campaign(account_id, campaign_id, minutes, campaign_name=None, db_path=DB_PATH):
    """Temporarily pause a campaign for `minutes`, then auto-resume. Sets paused_until
    = now + minutes; creates the schedule row if the campaign isn't already tracked
    (active stays 0 — a snooze doesn't enrol it in day-parting). Returns paused_until."""
    until = (datetime.now(timezone.utc) + timedelta(minutes=int(minutes))).isoformat()
    conn = get_db(db_path)
    existing = conn.execute(
        "SELECT 1 FROM ppc_campaign_schedule WHERE account_id=? AND campaign_id=?",
        (account_id, campaign_id)).fetchone()
    if existing:
        conn.execute(
            "UPDATE ppc_campaign_schedule SET paused_until=?, "
            "campaign_name=COALESCE(?, campaign_name), updated_at=? "
            "WHERE account_id=? AND campaign_id=?",
            (until, campaign_name, _now(), account_id, campaign_id))
    else:
        conn.execute(
            "INSERT INTO ppc_campaign_schedule (account_id, campaign_id, campaign_name, "
            "active, on_start_hour, on_end_hour, hour_mask, paused_until, updated_at) "
            "VALUES (?,?,?,?,?,?,?,?,?)",
            (account_id, campaign_id, campaign_name, 0, 0, 24, None, until, _now()))
    conn.commit()
    conn.close()
    return until


def clear_snooze(account_id, campaign_id, db_path=DB_PATH):
    """Cancel a temporary pause (resume normal schedule / on)."""
    conn = get_db(db_path)
    conn.execute(
        "UPDATE ppc_campaign_schedule SET paused_until=NULL, updated_at=? "
        "WHERE account_id=? AND campaign_id=?", (_now(), account_id, campaign_id))
    conn.commit()
    conn.close()


def account_for_campaign(campaign_id, db_path=DB_PATH):
    """Resolve which account a campaign belongs to (from the imported data) — used
    when the dashboard is viewing 'all accounts' and needs a concrete account to act."""
    conn = get_db(db_path)
    row = conn.execute(
        "SELECT account_id FROM ppc_search_terms WHERE campaign_id=? LIMIT 1",
        (campaign_id,)).fetchone()
    conn.close()
    return row["account_id"] if row else None


def upsert_schedule(account_id, campaign_id, campaign_name=None, active=None,
                    on_start_hour=None, on_end_hour=None, hour_mask=None, db_path=DB_PATH):
    """Create or update a campaign's schedule. Only non-None fields are changed."""
    conn = get_db(db_path)
    now = _now()
    existing = conn.execute(
        "SELECT * FROM ppc_campaign_schedule WHERE account_id=? AND campaign_id=?",
        (account_id, campaign_id)).fetchone()
    if existing:
        cur = dict(existing)
        vals = dict(
            campaign_name=campaign_name if campaign_name is not None else cur.get("campaign_name"),
            active=int(active) if active is not None else cur.get("active"),
            on_start_hour=int(on_start_hour) if on_start_hour is not None else cur.get("on_start_hour"),
            on_end_hour=int(on_end_hour) if on_end_hour is not None else cur.get("on_end_hour"),
            hour_mask=hour_mask if hour_mask is not None else cur.get("hour_mask"),
        )
        conn.execute("""UPDATE ppc_campaign_schedule SET campaign_name=?, active=?,
                        on_start_hour=?, on_end_hour=?, hour_mask=?, updated_at=?
                        WHERE account_id=? AND campaign_id=?""",
                     (vals["campaign_name"], vals["active"], vals["on_start_hour"],
                      vals["on_end_hour"], vals["hour_mask"], now, account_id, campaign_id))
    else:
        conn.execute("""INSERT INTO ppc_campaign_schedule
                        (account_id, campaign_id, campaign_name, active, on_start_hour,
                         on_end_hour, hour_mask, updated_at)
                        VALUES (?,?,?,?,?,?,?,?)""",
                     (account_id, campaign_id, campaign_name, int(active or 0),
                      int(on_start_hour if on_start_hour is not None else 0),
                      int(on_end_hour if on_end_hour is not None else 24), hour_mask, now))
    conn.commit()
    conn.close()


def get_schedules(account_id=None, active_only=False, db_path=DB_PATH):
    conn = get_db(db_path)
    w, p = _acct_where(account_id)
    if active_only:
        w = (w + " AND active=1") if w else " WHERE active=1"
    rows = conn.execute(
        f"SELECT * FROM ppc_campaign_schedule{w} ORDER BY campaign_name", p).fetchall()
    conn.close()
    return [dict(r) for r in rows]


def get_schedule(account_id, campaign_id, db_path=DB_PATH):
    conn = get_db(db_path)
    row = conn.execute(
        "SELECT * FROM ppc_campaign_schedule WHERE account_id=? AND campaign_id=?",
        (account_id, campaign_id)).fetchone()
    conn.close()
    return dict(row) if row else None


def set_last_desired_state(account_id, campaign_id, state, db_path=DB_PATH):
    conn = get_db(db_path)
    conn.execute("""UPDATE ppc_campaign_schedule SET last_desired_state=?, last_synced_at=?
                    WHERE account_id=? AND campaign_id=?""",
                 (state, _now(), account_id, campaign_id))
    conn.commit()
    conn.close()


def log_action(account_id, campaign_id, campaign_name, action, desired_state,
               result, detail=None, db_path=DB_PATH):
    conn = get_db(db_path)
    conn.execute("""INSERT INTO ppc_action_log
                    (account_id, campaign_id, campaign_name, action, desired_state, result, detail, at)
                    VALUES (?,?,?,?,?,?,?,?)""",
                 (account_id, campaign_id, campaign_name, action, desired_state,
                  result, detail, _now()))
    conn.commit()
    conn.close()


def get_action_log(account_id=None, limit=200, db_path=DB_PATH):
    conn = get_db(db_path)
    w, p = _acct_where(account_id)
    rows = conn.execute(
        f"SELECT * FROM ppc_action_log{w} ORDER BY at DESC LIMIT {int(limit)}", p).fetchall()
    conn.close()
    return [dict(r) for r in rows]


def campaign_names(account_id=None, db_path=DB_PATH):
    """Distinct campaigns seen in the Search Term data — the pick-list for
    scheduling (so you schedule real campaign IDs, not typed strings)."""
    conn = get_db(db_path)
    w, p = _acct_where(account_id)
    rows = conn.execute(f"""
        SELECT campaign_id, MAX(campaign_name) AS campaign_name,
               ROUND(SUM(spend),2) AS spend
        FROM ppc_search_terms{w}
        GROUP BY campaign_id ORDER BY SUM(spend) DESC
    """, p).fetchall()
    conn.close()
    return [dict(r) for r in rows]


def by_search_term(account_id="all", limit=500, db_path=DB_PATH):
    conn = get_db(db_path)
    w, p = _acct_where(account_id)
    rows = conn.execute(f"""
        SELECT search_term, targeting_type,
               COUNT(DISTINCT campaign_id) AS campaigns,
               SUM(impressions) AS impressions, SUM(clicks) AS clicks,
               ROUND(SUM(spend),2) AS spend, SUM(orders) AS orders, ROUND(SUM(sales),2) AS sales
        FROM ppc_search_terms{w}
        GROUP BY search_term, targeting_type
        ORDER BY SUM(spend) DESC
        LIMIT {int(limit)}
    """, p).fetchall()
    conn.close()
    return [dict(r) for r in rows]


def by_campaign(account_id="all", db_path=DB_PATH):
    conn = get_db(db_path)
    w, p = _acct_where(account_id)
    rows = conn.execute(f"""
        SELECT campaign_id, campaign_name,
               COUNT(DISTINCT search_term) AS terms,
               SUM(clicks) AS clicks, ROUND(SUM(spend),2) AS spend,
               SUM(orders) AS orders, ROUND(SUM(sales),2) AS sales
        FROM ppc_search_terms{w}
        GROUP BY campaign_id, campaign_name
        ORDER BY SUM(spend) DESC
    """, p).fetchall()
    conn.close()
    return [dict(r) for r in rows]
